// Copyright (C) 2011,2012 CNRS-LAAS
// Author: Sebastien Dalibard.
//
// This file is part of the hpp-wholebody-step-corba.
//
// hpp-wholebody-step-corba is free software: you can redistribute
// it and/or modify it under the terms of the GNU Lesser General
// Public License as published by the Free Software Foundation, either
// version 3 of the License, or (at your option) any later version.
//
// hpp-wholebody-step-corba is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public
// License along with hpp-wholebody-step-corba.  If not, see
// <http://www.gnu.org/licenses/>.

#ifndef HPP_TIMEOPT_CORBA_IDL
#define HPP_TIMEOPT_CORBA_IDL

# include <hpp/corbaserver/common.idl>

module hpp {
  module corbaserver {
  module timeopt {
  interface Problem {


    void setTimeOptPlanner(in string cfg_path, in string default_path) raises (Error);
    void setInitialBodyState() raises (Error);
    void setInitialLimbState(in string joint_name, in boolean activation, in unsigned short ID, in floatSeq force_ratio) raises (Error);
    void addContactSequence(in unsigned short id, in floatSeqSeq footstep) raises (Error);
    void calculate() raises (Error);
    void setFinalBodyState(in floatSeq com) raises (Error);
    void setFinalBodyStatfromConfig(in floatSeq posture) raises (Error);

    unsigned short getNumSeqeunce() raises (Error);
    floatSeq getResultantBodyDynamics(in unsigned short cnt) raises (Error);
    floatSeq getResultantLimbDynamics(in unsigned short cnt, in unsigned short id) raises (Error);
    floatSeq getEndeffectorTransform(in string limb_name, in floatSeq configuration) raises (Error);
    floatSeq getComFromRobot(in floatSeq configuration) raises (Error);        
  }; //interface Problem
  }; // module timeopt
  }; // module corbaserver
}; // module hpp

#endif // HPP_TIMEOPT_CORBA_IDL
